production:
  adapter: mysql2
  database: access_lab
  host: 127.0.0.1
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  username: root
  password: "mrvo722tun"

development:
  adapter: mysql2
  database: access_lab
  host: 127.0.0.1
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  username: root
  password: "mrvo722tun"
  pool: 20

test:
  adapter: mysql2
  database: access_lab_test
  host: 127.0.0.1
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  username: root
  password: "mrvo722tun"

